- hosts: kubemaster,kubeworkers
  become: yes
  become_user: root
  tasks:

   - name: Install prerequisites
     apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      update_cache: yes

   - name: Add Docker GPG key
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg

   - name: Add Docker APT repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

   - name: Install Docker
     apt:
      name: docker-ce=18.06.0*
      update_cache: yes

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet=1.14.0-00
       state: present
       update_cache: true

   - name: get docker cgroup driver
     shell: grep "ExecStart=" /lib/systemd/system/docker.service
     register: docker_execstart
     ignore_errors: True

   - name: change cgroup driver to systemd
     lineinfile:
      path: /lib/systemd/system/docker.service
      regex: ^(.*?(\bExecStart\b)[^$]*)$
      line: "{{docker_execstart.stdout}} --exec-opt=native.cgroupdriver=systemd" 

   - name: restart docker
     systemd: 
      name: docker
      state: restarted
      daemon_reload: yes

   - name: install kubeadm
     apt:
       name: kubeadm=1.14.0-00
       state: present

   - name: Disable SWAP since kubernetes cant work with swap enabled (1/2)
     shell: swapoff -a
      
   - name: Disable SWAP in fstab since kubernetes cant work with swap enabled (2/2)
     replace:
       path: /etc/fstab
       regexp: '^(.+?\sswap\s+sw\s+.*)$'
       replace: '# \1'
