---
- hosts: kubemaster
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: write to local
      become_user: ansible
      local_action: copy content="{{join_command_raw.stdout_lines[0]}}" dest="/home/ansible/variable"

- hosts: kubeworkers
  become: yes
  vars:
   contents: "{{ lookup('file', '/home/ansible/variable') }}"
  tasks:
    - name: join cluster
      become_user: root
      shell: "{{contents }} >> node_joinedtest.txt"
      args:
        chdir: $HOME
        creates: node_joinedtest.txt
...
